### ISSUE TITLE
ruby_version shows null

### ISSUE THREAD

**Issue by gameforce** [wearefine/puppet-jenkins-shared-libraries#4]
Not sure if I missed something in my setup but I keep getting this error:
```
12:23:04  + bash -c source /usr/local/rvm/scripts/rvm && rvm use --install --create null@puppet && bundle install
12:23:04  Unknown ruby interpreter version (do not know how to handle): null.
```
Seems that no matter what I try RUBY_VERSION does not get picked up by the script

Not sure what to do, help?

**Comment by cpitkin** [comment]
@gameforce Sorry for the late reply. 
For starters can you post your Jenkinsfile so I can see what your inputs are put into the pipeline?
I believe I have found an error where the config.RUBY_VERSION isn't getting passed into the pipeline from the Jenkinsfile. I no longer work with Jenkins on a regular basis but I'll get this fixed.

**Comment by cpitkin** [comment]
@gameforce I added the update on master. PR #5 is ready to merge. I'm not able to test out the changes locally so if you would test it out that would be great. You can pull in the master branch in Jenkins shared library configuration.

**Comment by gameforce** [comment]
This fixed the the version but now it can't find a gemfile, here's the relevant log output from the job:

03:15:58  [Pipeline] }
03:15:59  [Pipeline] // stage
03:15:59  [Pipeline] echo
03:15:59  BRANCH_NAME: production
03:15:59  [Pipeline] fileExists
03:15:59  [Pipeline] stage
03:15:59  [Pipeline] { (Install Dependancies)
03:15:59  [Pipeline] milestone (Install Dependancies)
03:15:59  Trying to pass milestone 0
03:15:59  [Pipeline] retry
03:15:59  [Pipeline] {
03:15:59  [Pipeline] sh
03:15:59  + bash -c source /usr/local/rvm/scripts/rvm && rvm use --install --create ruby-2.3.0@puppet && bundle install
03:15:59  Using /var/jenkins_home/.rvm/gems/ruby-2.3.0 with gemset puppet
03:16:00  Could not locate Gemfile
03:16:00  [Pipeline] }
03:16:00  ERROR: script returned exit code 10
03:16:00  Retrying
03:16:00  [Pipeline] {
03:16:00  [Pipeline] sh
03:16:01  + bash -c source /usr/local/rvm/scripts/rvm && rvm use --install --create ruby-2.3.0@puppet && bundle install
03:16:01  Using /var/jenkins_home/.rvm/gems/ruby-2.3.0 with gemset puppet
03:16:01  Could not locate Gemfile
03:16:01  [Pipeline] }
03:16:01  [Pipeline] // retry
03:16:01  [Pipeline] }
03:16:01  [Pipeline] // stage
03:16:01  [Pipeline] }
03:16:01  [Pipeline] // timestamps
03:16:01  [Pipeline] }
03:16:01  [Pipeline] // node
03:16:01  [Pipeline] End of Pipeline
03:16:01  ERROR: script returned exit code 10
03:16:01  Finished: FAILURE

It's no problem I can do more tests if you need.

Thanks

**Comment by cpitkin** [comment]
@gameforce 'll take a look this weekend. In the meantime maybe check that your Gemfile is in your project root. Obvious I know, but never hurts to check.

**Comment by cpitkin** [comment]
@jamesmk or @victorhundo do one of you have bandwidth to take a look at this. I'm not going to be get it for a couple weeks.
